### ISSUE TITLE
Initial rendered value with repeater

### ISSUE THREAD

**Issue by mainpart** [nk-crew/lazy-blocks#120]
Insertion of repeater row does not pass to server render initialy selected value of select box

![image](https://user-images.githubusercontent.com/2713266/74733376-c7394e80-527e-11ea-901b-9145221c8d5a.png)

dump of xhr request event (to /wp-json/lazy-blocks/v1/block-render) shows that 3rd row content is empty

![image](https://user-images.githubusercontent.com/2713266/74733314-a7098f80-527e-11ea-8533-360436f53adc.png)

**Comment by nk-o** [comment]
Unfortunately, default values of repeater items are not supported at all.
![image](https://user-images.githubusercontent.com/14810891/75345324-8f995a80-58ad-11ea-8c00-669b46f7177d.png)

**Comment by mainpart** [comment]
Not sure if it is about default value. I'm not using it. 

It's about first value. My select contains some items so when i'm inserting row it inserts select with the first value selected automaticaly. 
It's not null, not empty and it's not default. 

It's just first value in pre-defined select block and it pass to server as empty.

**Comment by nk-o** [comment]
You added options to select field, but it doesn't mean, that it has a default value by default. It just displayed the first available option in the select field, nothing special.

I recommend you enable this setting for now:

![image](https://user-images.githubusercontent.com/14810891/75429332-a944ab80-595a-11ea-9b39-99219839964c.png)

It will add this new option:

![image](https://user-images.githubusercontent.com/14810891/75429574-0f313300-595b-11ea-815b-a9a369a6d661.png)

But I see another bug :) It will save the value '-- Select --' when you manually select this first value... It will be fixed soon :)

**Comment by andrewgolovanov** [comment]
Hi guys!
I'm still experiencing this problem described above :( 
is there any news on its solution?

Thanks!

**Comment by andrewgolovanov** [comment]
Hi guys!

I'd like it if the field is required, then the user must select a value from a list, but at this point, we can select `-Select-`, which should essentially be an empty value (not selected) and notify me that the field is required and I must select a value from the list that is not `-Select-`, but unfortunately, this does not work properly

I think we could solve this with an empty default value - which I understand is not currently supported :(

<img width="827" alt="Снимок экрана 2021-11-12 в 17 50 41" src="https://user-images.githubusercontent.com/17677196/141489149-dece86e1-bca6-46fe-a373-38d12744b383.png">

**Comment by nk-o** [comment]
In the v3 we added support for default control values inside the repeater. Defaults are inserted automatically once you add the row.
