### ISSUE TITLE
&quot; quotes in description

### ISSUE THREAD

**Issue by mainpart** [nk-crew/lazy-blocks#121]
![image](https://user-images.githubusercontent.com/2713266/75420238-35120400-596a-11ea-9749-f39c7a88fb65.png)

Incorrect quoting of special chars when saving description with quotes. Maybe will fix myself and make a PR.

**Comment by nk-o** [comment]
I just can't reproduce it... Quotes always saving properly.

**Comment by nk-o** [comment]
Still can't reproduce this issue. Since we changed a lot in the latest release and added support for HTML tags inside the description, this bug must be fixed automatically. If not, please reopen the issue with the steps to reproduce it.
