### ISSUE TITLE
Get post data in admin

### ISSUE THREAD

**Issue by sandromattei** [nk-crew/lazy-blocks#125]
Hi,

I need to create a block that shows the title of the post.
How can I insert the post title in the block attributes?
Thank you

**Comment by serhumanos** [comment]
Hi, this code works for me:

```
<?php global $wp_query; ?>

<h1 class="title"><?php echo get_the_title($wp_query->posts[0]->ID) ?></h1>
```

**Comment by nk-o** [comment]
Closing, as the wp_query automatically added to the block preview and it is possible to use block code like this:

```
<?php
echo get_the_title();
```
