### ISSUE TITLE
[Question] Color picker - output color slug?

### ISSUE THREAD

**Issue by nicar** [nk-crew/lazy-blocks#126]
Just started to play around a bit (love it so far!) and was wondering if there is any possibility to output the color slug from the block palette when the color picker is used?
As in https://developer.wordpress.org/block-editor/developers/themes/theme-support/#block-color-palettes

Using classes according to the ".has-{$color-slug}-color" scheme could be nice in some cases.

**Comment by nk-o** [comment]
Hey.

Currently, it is not possible without custom coding.

I think in the future updates it may be added as an option for Color control with output format:
```php
array(
	'color': '#fff',
	'slug': 'white',
)
```

**Comment by fishmi** [comment]
+1 for this feature
This could simply avoid poorly maintainable inline css code

**Comment by nk-o** [comment]
+1 from this topic https://wordpress.org/support/topic/color-picker-option-to-use-class-instead-of-hex/

I think I will develop this feature in the next plugin update.

**Comment by davidwebca** [comment]
I made a quick and dirty function to return the slug.

```
function palette_to_slug($color) {
    $support_palette = get_theme_support( 'editor-color-palette' );

    $slug = null;
    if(!empty($support_palette)) {
        $palette = $support_palette[0];
        $palette_reversed = wp_list_pluck( $palette, 'slug', 'color' );
        if(isset($palette_reversed[$color])) {
            $slug = $palette_reversed[$color];
        }
    }

    return $slug;
}
```

 but it could also return different formats like the text and background classes from WordPress like [this ACF field plugin](https://github.com/Log1x/acf-editor-palette)
