### ISSUE TITLE
UI: add option to visually group fields (in tabs, for example).

### ISSUE THREAD

**Issue by pagelab** [nk-crew/lazy-blocks#15]
With blocks containing lots of fields, this would help to organize them better by affinity or function.

Having all of them simply laid out one after the other can confuse the user.

Here's one quick mockup with section tabs on the block's left side:

![lazy-blocks-with-sections](https://user-images.githubusercontent.com/1451087/47314366-d02cf800-d617-11e8-8797-e115570b43d1.png)

**Comment by nk-o** [comment]
Related topic: https://wordpress.org/support/topic/ui-add-option-to-visually-group-fields-in-tabs-for-example/

**Comment by nk-o** [comment]
Another request is to add PanelBody Gutenberg components https://wordpress.org/support/topic/feature-request-group-fields/, https://github.com/nk-o/lazy-blocks/issues/128

**Comment by nk-o** [comment]
Panels and dividers are available in the Lazy Blocks Pro https://www.lazyblocks.com/pro/, we will also consider making tabs, as requested in this issue
