### ISSUE TITLE
Strange output with repeater

### ISSUE THREAD

**Issue by NielsWPN** [nk-crew/lazy-blocks#173]
Hi

### Issue description:
I use a repater in a block containing other fileds. I try to mask the output of the repeater fileds if they are not filled with if($attributes['control-name']) (using theme template) but this doesn't work: the div containing those fields keeps showing. If I try to make the condition deeper in the array I get some problems with other meta fields and more that I cannot identify. I tired to output the repeater content array (shown below) and it shows that some extra elements are included in it if it is empty – thus I guess the if($ condition not working. What goes wrong ?

### Lazy Blocks Version:
Latest (2.2.0)

### WordPress Version:
Latest (5.5.1)

### Any helpful information to reproduce the issue (screenshots, code parts)

Uncompleted Repeater field array output (<?php print_r($attributes['conceptrices']); ?>) :
Array ( [0] => Array ( [prenom-nom] => [occupation] => [lazyblock] => Array ( [slug] => lazyblock/contenu-ateliers ) [className] => [align] => [anchor] => [blockId] => [blockUniqueClass] => [ghostkitSpacings] => [ghostkitSR] => ) ) 

Completed Repeater field array output (same code as above, output correct - as expected):
Array ( [0] => Array ( [prenom-nom] => Name Surname [occupation] => Occupation ) [1] => Array ( [prenom-nom] => Name Surname [occupation] => Occupation ) [2] => Array ( [prenom-nom] => Name Surname [occupation] => Occupation ) ) 

(I haven't installed GhostKit)
------------
Best regards

**Comment by nk-o** [comment]
Hey.  
  
Your repeater attribute is an empty array. Try to check it like this:

```
if ( ! empty( $attributes['control-name'] ) ) {
    // ...
}
```

**Comment by NielsWPN** [comment]
Hi

Thank you for your answer. But it doesn't work… your code still fires because something is in the array.

! empty ( $attributes['control-name'][0] ) also fires

BUT

! empty ( $attributes['control-name'][1] )  correctly fires only when there is the content I need

Maybe a database cache or I don't know

Best

Niels

**Comment by nk-o** [comment]
Hey.  
  
Could you create a private ticket in our support system https://nk.ticksy.com/ in the Bug Reports category?

**Comment by nk-o** [comment]
should be fixed in https://github.com/nk-crew/lazy-blocks/commit/02a757fd5c878e2c0e21015091ce599d882bab7c
