### ISSUE TITLE
Page cannot be filled with any blocks. core/free inserted by default

### ISSUE THREAD

**Issue by enriquemorenotent** [nk-crew/lazy-blocks#175]
### Issue description:
When I create a new page, the interface presented allows me to set the title, but it is not possible to click anywhere to add blocks.

If I switch to the code editor for the page I see that the page was prefilled with this code:

```
<!-- wp:lazyblock-core/free /-->
```

I have tried deleting this code, and return to the visual editor, but I am still unable to add blocks to the page.

What is happening? How come my page is pre-populated with this element, and why can't I add any blocks to the page?

Notice this **only happens for pages**. Not for posts.

### Lazy Blocks Version:
2.1.1

### WordPress Version:
5.5.1

**Comment by nk-o** [comment]
Have you added a custom Template with a lock?

![](https://user-images.githubusercontent.com/14810891/97223229-88ca3b00-17e0-11eb-91a0-35485f53d849.png)
