### ISSUE TITLE
[Feature Request] Templates for specific post/page template

### ISSUE THREAD

**Issue by adam-laita** [nk-crew/lazy-blocks#181]
Hi LB team,
if it's interesting to you, would you consider more options for templates conditions? For example, if I have a home page, I need to create a template with specific blocks, but for other pages I need to have blocks without restrictions.

Thanks for any response
Adam

**Comment by nk-o** [comment]
Hey Adam.

Yep, this feature is interesting, but I don't know when it may be implemented. It has a low priority for now.

**Comment by TheALuminium** [comment]
I understand that so perhaps in the near future :) ... anyway and I'm looking forward for PRO version, if you need some beta testers I volunteer.

**Comment by lnikell** [comment]
Upvote this feature too, it will make templates section useful 😁

**Comment by AndrewKirpanev** [comment]
Upvote this feature 🔥

**Comment by Correct-Syntax** [comment]
Upvote to this +1

**Comment by nk-o** [comment]
Closed because Gutenberg already offers a method for managing templates. Lazy Blocks' template feature will be deprecated soon.
