### ISSUE TITLE
The meta data of the set default value of the unused block is saved

### ISSUE THREAD

**Issue by qige33** [nk-crew/lazy-blocks#190]
### Issue description:
I found that in the new version (2.3.1) of the plug-in, some blocks that have selected "save in meta" and set default values, will save meta data in the "postmeta" table of the database even if they are not used when creating a new article , so the judgment syntax of some of my PHP code is all invalid.

### Lazy Blocks Version:
2.3.1

### WordPress Version:
WordPress 5.7

**Comment by nk-o** [comment]
We have to register meta in order to use it in the block context. And there is the only way, by using this function https://developer.wordpress.org/reference/functions/register_meta/, which creates defaults.
