### ISSUE TITLE
Critical error on WP admin page

### ISSUE THREAD

**Issue by westhamsid0999** [nk-crew/lazy-blocks#192]
### Issue description:
Getting a critical error on the wp-admin page that i have added lazy blocks to, It seems to happen randomly, Doesnt affect the live page (just the wp admin page), Once it happens i cannot access the page and have to create a new one. After duplicating, I can see the characters used in my shortcodes have become gobbledygook.

### Lazy Blocks Version:
2.3.1 (latest)

### WordPress Version:
5.7

### Any helpful information to reproduce the issue (screenshots, code parts)

![image](https://user-images.githubusercontent.com/81263248/112211608-03727780-8c14-11eb-98c3-55ac3bf8becc.png)

**Comment by nk-o** [comment]
Hey.  
  
Please, enable WP_DEBUG [codex.wordpress.org/WP_DEBUG](https://codex.wordpress.org/WP_DEBUG), and once an error appears, you can see more information about it. Please, provide it here. Until then I don't know how to help you.
