### ISSUE TITLE
Switch between editor and preview

### ISSUE THREAD

**Issue by merijnponzo** [nk-crew/lazy-blocks#194]
In the current version both content and preview is shown.
It would be super nice if there would be an edit and preview button in the top toolbar of each block to switch between either editing, or previewing the content

**Comment by merijnponzo** [comment]
And with an extra previewServerCallback for example onToggle
this would mean I can properly mount my Vue components
Now I use onChange and they are mounted on every change :-|

for example 'lzb.components.PreviewServerCallback.onToggle'
with a props.toggleMode = 'preview'

```
// lazyblocks components
const LazyblockComponents = ['tabs']
  wp.hooks.addAction(
    'lzb.components.PreviewServerCallback.onToggle',
    comp,
    function (props) {
      const el = document.getElementsByClassName(
        props.attributes.blockUniqueClass
      )
      if (el.length && props.toggleMode === 'preview' ) {
        const app = createApp({ template: preview[0].innerHTML })
        app.component('Tabs', Tabs)
        app.mount(preview[0])
      }
    })

```

**Comment by nk-o** [comment]
We're closing this issue because we won't be using the switch method. We'll gradually phase out the Content placement for controls. While it will still be supported, we won't recommend using it. I suggest using Inspector controls instead, as they offer a more native approach.
