### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by vinayraghu** [nk-crew/lazy-blocks#195]
### Issue description:

Hi, a few simple questions because I couldn't find any links online so opening an issue. I've used this in a project and it has been great! 

* How do I create one block.php file and use it to power both editor and frontend? 
* How do I force a block to only be full width in the editor? 
* Is it possible to create the block frontend code using JS / React instead of PHP? 
* What is the plan for the PRO version? Would like to pay so there's support / SLA if needed. 
* How do I customize the icons (use a downloaded SVG file) for a block? 

Appreciate your help!

**Comment by merijnponzo** [comment]
```
<?php
$theme = Ponzo::blockTheme('tabs', $attributes['blocktheme']);
$content = Ponzo::blockSafeHtml($attributes['tabs'],'text');
?>
<Tabs 
:theme='<?=json_encode($theme);?>'
:content='<?=json_encode($content);?>'
>
</Tabs>
```
Where Tabs is my Vue component, sure something would work for react as well 
I had to use php 'htmlentities' to format rich context before encoding it into my compnent

**Comment by nk-o** [comment]
Hey.

1. Just create the block.php and it will work for both sides https://lazyblocks.com/documentation/blocks-code/theme-template/
2. I'm not sure it is possible without JS customizations. I have added this to our issue tracker, maybe in future updates such feature will be added.
3. Why not, it is custom output, you may output what you want to.
4. We have plans, but it is not yet in our highest priority, so I don't know when exactly it will be released.
5. It is only possible with exported to PHP blocks. I have also added this feature to our issues tracker.

Regards, nK.
