### ISSUE TITLE
Line breaks in Text Area Field are not rendered

### ISSUE THREAD

**Issue by szopos** [nk-crew/lazy-blocks#196]
Line Breaks are not rendered in Text Area fields… unless I type `<br>` . So far so good. When I type the same in the "Default Value" of that field, lazy blocks removes the `<br>`. To be consistent: the "Default Value" field should be also a text area field and accept (regular or `<br>`) line breaks.

Lazy Blocks Version: 2.3.1
WordPress Version: 5.7

<img width="585" alt="grafik" src="https://user-images.githubusercontent.com/2480612/112975403-e1b54b00-9153-11eb-81b5-95bbb38a4fa1.png">

**Comment by szopos** [comment]
To be even more consistent: the "Placeholder" field should be also a text area field.

**Comment by nk-o** [comment]
In the latest update some of the control fields now can render HTML tags and you issue should be fixed now
