### ISSUE TITLE
Enhancement: Add support for showing/hiding fields with a toggle field

### ISSUE THREAD

**Issue by Knogobert** [nk-crew/lazy-blocks#20]
Love the work you’ve done!

I think there is a bigger use case that is available in ACF (Conditional Logic) that should become available soon enough in Lazy Blocks as well. 
It is support for showing and hiding other fields in the back-end, depending on the state of a toggle or such (checkbox, dropdown select). 

Here's an example case where it is dearly needed for the user experience of the back-end:

![screenshot 2018-11-06 at 10 43 56](https://user-images.githubusercontent.com/770560/48056611-6df4fb00-e1b2-11e8-8657-23cbd6b3d28e.png)

Keep up the good work and this plugin can become huge 🙃 !

**Comment by AdsonCicilioti** [comment]
Yep! Nice feature!

**Comment by NRDay** [comment]
+1 Would also like to see this feature.

**Comment by jaapie1989** [comment]
+1 Really in need of this function.  Love the work you have done!

**Comment by matt3224** [comment]
@nk-o any progress on this one?

**Comment by nk-o** [comment]
@matt3224 not yet. Busy on our other plugin right now.

**Comment by biabel** [comment]
@nk-o 
Dear Lazyblocks Team,

what is the current status of this?
Will this function be available?

If so, when could this function be available?

This feature would take Lazyblocks to the next level and make it much better! 

Very good work from you guys so far! I love your plugin :)

**Comment by nk-o** [comment]
Hey @biabel . This feature will be a part of Pro plugin. Currently, we don't have any ETA for this.

**Comment by nk-o** [comment]
This feature is available in the Lazy Blocks Pro https://www.lazyblocks.com/pro/
