### ISSUE TITLE
the editor has encountered an unexpected error

### ISSUE THREAD

**Issue by xxmiz0rexx** [nk-crew/lazy-blocks#201]
### Issue description:
After I updated WordPress to the latest version (2.3.1), I can't save the content anymore.

### Lazy Blocks Version:
2.3.1

### WordPress Version:
5.7.1

### Any helpful information to reproduce the issue (screenshots, code parts)
![image](https://user-images.githubusercontent.com/7021949/115502630-30b45300-a2b0-11eb-8147-2ffb146a4b63.png)

![image](https://user-images.githubusercontent.com/7021949/115504157-707c3a00-a2b2-11eb-937f-82fac61b3abb.png)

**Comment by nk-o** [comment]
Hey. To reproduce this issue locally I need more info. Which type of blocks used, which plugins, what exactly you trying to save, etc, etc...
