### ISSUE TITLE
custom helpers, working with key val array

### ISSUE THREAD

**Issue by Adam-Collier** [nk-crew/lazy-blocks#210]
Hey there! First of all thanks for creating this great plugin, it's really nice to work with. I want to ask about a couple of things when it comes to custom helpers. Firstly, in the custom helper example it renders the p tags as a string, is there a way so it renders the tags correctly? And secondly is there a way we can create a custom helper that returns an array with key => values which we can then render using the key? Essentially I want to do a loop through multiple selected items but retain and render the unselected items but giving the selected items an active class. 

This questions answer solves what I want to achieve: https://stackoverflow.com/questions/42320190/return-array-of-objects-from-handlebars-helper 

however my own implementation in php doesn't seem to work:

```php
function terr_handlebars_helper ( $handlebars ) {
    $handlebars->registerHelper( 'terr', function( $arg1, $options ) {
		$territories = ["AU", "DE", "ES", "EU", "FR", "IE", "PL", "UK", "US"];

		$result = [];

		foreach($territories as $territory) {
			if(in_array($territory, $arg1)){
				$result[] = $options[fn](["territory" => "uk", "active" => true]);
			} else {
				$result[] = $options[fn](["territory" => $territory, "active" => false]);
			}
		}

		return $result;
    });
}

add_action( 'lzb/handlebars/object', 'terr_handlebars_helper' );
```
If you can offer some guidance/clarification on this that would be great, and thanks again for all your hard work on this!

**Comment by nk-o** [comment]
Hey.

To render unsafe HTML, you just have to use triple `{`, like so `{{{test}}}`. https://lazyblocks.com/documentation/blocks-controls/rich-text-wysiwyg/

What about helper with returning an array, tbh I don't know. An example on StackOverflow shows that the helper returns the string, not the array.

Regards, nK.

**Comment by Adam-Collier** [comment]
Great thanks for sharing! FYI I did manage to get the array stuff working, we can do something like the below:

```php
function terr_handlebars_helper ( $handlebars ) {
    $handlebars->registerHelper( 'terr', function( $arg1, $options ) {
		// all of the territories we want to show
		$territories = ["AU", "DE", "ES", "EU", "FR", "IE", "PL", "UK", "US"];

		$buffer = "";

		$context = $options['context'];
		$template = $options['template'];

		foreach($territories as $territory) {
			if(in_array($territory, $arg1)){
				$context->push(array("territory" => $territory, "active" => true));
			} else {
				$context->push(array("territory" => $territory, "active" => false));
			}

			$buffer .= $template->render($context);
		}

		return $buffer;
    });
}
```
The general idea was taken from [here](https://github.com/XaminProject/handlebars.php/blob/master/src/Handlebars/Helper/EachHelper.php). Then in our handlebars we can do this (the territories here are from a multiple select):

```html
<ul>
      {{#terr territories}}
        <li {{#if active}}class="active"{{/if}}>{{territory}}</li>
      {{/terr}}
</ul>
```

Hopefully this helps anyone else who comes across this problem
