### ISSUE TITLE
Move jQuery to footer issue

### ISSUE THREAD

**Issue by iamalessiopaoletti** [nk-crew/lazy-blocks#213]
Hi,

I have installed the plug-is, but I have a problem in the back-end when i open add block page, nothing is loaded, because i have this code in function.php for load jquery in the footer and not in the head of the page:

        remove_action( 'wp_head', 'print_emoji_detection_script', 7 );
	remove_action( 'wp_print_styles', 'print_emoji_styles' );
	wp_dequeue_script('jquery');
	wp_dequeue_script('jquery-core');
	wp_dequeue_script('jquery-migrate');
	wp_enqueue_script('jquery', false, array(), false, true);
	wp_enqueue_script('jquery-core', false, array(), false, true);
	wp_enqueue_script('jquery-migrate', false, array(), false, true);

how can I solve?

**Comment by nk-o** [comment]
I'm not sure you can do this safely in the admin area. You should move this code to the frontend.
