### ISSUE TITLE
Control type „rich text” not working 

### ISSUE THREAD

**Issue by insi189746** [nk-crew/lazy-blocks#217]
### Issue description:

The control type „rich text” no longer works in the Gutenberg Editor since last update.

**Comment by nk-o** [comment]
Hey.

I don't see any problem here. If you have more info to reproduce this issue, please, provide it and reopen this issue.

![image](https://user-images.githubusercontent.com/14810891/132509307-0933ad95-29af-4701-96f4-5d4e8440bf1e.png)

**Comment by davidwebca** [comment]
I previously had issues where the formatting bar was not showing up if the control was set in the sidebar, but I would need to test it out again since I had just given up and put the control in the content.

**Comment by nk-o** [comment]
I think this component is not displaying the toolbar in the sidebar by design. This can't be fixed, since this is a standard Gutenberg component.

**Comment by insi189746** [comment]
In fact, the rich text editor in the content area does work but not if the control is set to sidebar. The toolbar in the sidebar was displaying before update. I also have an older project where it is also working when set to sidebar:

![image](https://user-images.githubusercontent.com/73293169/134921004-aa11e3b7-a064-49e7-ab32-596dcf05475a.png)
