### ISSUE TITLE
Color Picker not returning Slug

### ISSUE THREAD

**Issue by CGTS** [nk-crew/lazy-blocks#228]
### Issue description:
I've followed this example in the documentation https://lazyblocks.com/documentation/blocks-controls/color-picker/ but I can never get it to return the slug ```{{something.slug}}``` . Everything works fine with ```{{something.color}}```

### Lazy Blocks Version:
2.5.1

### WordPress Version:
5.8.2

**Comment by nk-o** [comment]
Hey.

Tested it and it is working fine... Please, provide any helpful info to reproduce this issue locally

![image](https://user-images.githubusercontent.com/14810891/142723842-fda12276-5a62-4359-82ca-b8894dfe5401.png)

![image](https://user-images.githubusercontent.com/14810891/142723868-a4774fac-fad7-42fb-a874-b15fc7b78e60.png)

**Comment by CGTS** [comment]
@nk-o  I recreated what you sent above with no change. I double checked my theme. json and there doesn't seem to any issues there. Is there some other information that would help?

```
"color": {
  "palette": [{
    "name": "gray-50",
     "slug": "gray-50",
      "color": "#f5f5f4"
       }, ...
```

![edit-block](https://user-images.githubusercontent.com/10124340/142742221-0725dd2d-2586-418c-8492-43546e909278.png)

![color-block](https://user-images.githubusercontent.com/10124340/142742222-33fdee9f-cf15-41df-a43a-bdea2f469af6.png)

**Comment by nk-o** [comment]
@CGTS thank you for mentioning this detail - this is the latest Gutenberg API for themes, with which I have never tested our plugin. I will look at it and try to fix 😉
