### ISSUE TITLE
Separator for Inspector and Content Controls

### ISSUE THREAD

**Issue by biabel** [nk-crew/lazy-blocks#231]
Hello,
is it possible to integrate subdivisions/Separator (accordion or lines) for the Inspector and Content Controls? 
So that the fields can be better structured?

Thank you and best regards
Biabel

**Comment by nk-o** [comment]
Hey Biabel.

I will close your issue, as there is another one with almost the same problem - https://github.com/nk-crew/lazy-blocks/issues/15

We will make separators in the Pro addon, but it is not yet ready to ship...

**Comment by biabel** [comment]
@nk-o 
Hey,
oh sorry I had not seen that...

Is there already a date for the release of the Pro version or already a beta version?

We are very interested in it! :)

**Comment by nk-o** [comment]
@biabel no problem, this missing feature is a pain and most users want it for a long time.

No, there is no ETA for release. We are only 3 men and don't have much time done the lazy blocks pro, we are focused on the projects, which already generate money for us (Themeforest themes and Visual Portfolio plugin).

But I hope we will release it until summer...

**Comment by biabel** [comment]
@nk-o 

Okay, thanks for the quick responses.

Wish you continued success and keep up the good work! :)
