### ISSUE TITLE
After Duplicate a Page / Post - the WYSIWYG Tags are escaped

### ISSUE THREAD

**Issue by sbdgithub** [nk-crew/lazy-blocks#235]
### Issue description:

When I duplicate a page or post (Plugins: "Duplicate Page" or "Duplicate Pages, Posts & CPT") then the contents of the WYSIWYG fields are displayed incorrectly (unicode escapes are displayed instead of the tags).

Does anyone have this problem too?

Many Thanks

### Lazy Blocks Version:

Version 2.5.3

### WordPress Version:

Version 5.9

### Any helpful information to reproduce the issue (screenshots, code parts)

![lazy-copied](https://user-images.githubusercontent.com/69640549/154519571-adf9d7f4-e04b-47d3-ad63-6eb9741570d5.png)

**Comment by plueschpruem** [comment]
Oh thanks!
This happened to me as well lately and I was wondering how it came about.

**Comment by nk-o** [comment]
There's little interest in this issue. It can probably be resolved by "duplicate" plugin authors itself.
