### ISSUE TITLE
Hide if block is not selected not hiding input fields

### ISSUE THREAD

**Issue by nickfmc** [nk-crew/lazy-blocks#243]
Ideally in the backend preview I would want to hide my controls when the block is not selected, and it sound like the "Hide if block is not selected" toggle would do this. however changing that toggle doesn't seam to affect anything as far as I can tell?

**Comment by nk-o** [comment]
Hey.

This is how this should work:

https://user-images.githubusercontent.com/14810891/173082731-38ba3ab0-c33c-4a86-be52-1021259629bd.mp4

Is it not working on your site?

**Comment by nickfmc** [comment]
correct, that's the awesome functionality that would make this better than ACF blocks ;)  here is a video maybe I am missing something? I tested with no plugin and 2022 theme also.

https://user-images.githubusercontent.com/8106386/173206221-2586405b-c7c1-473e-9876-48e9234b6e40.mp4
