### ISSUE TITLE
Convert acf / custom fields to block attributes

### ISSUE THREAD

**Issue by hj-collab** [nk-crew/lazy-blocks#248]
Hi. It's a feature request for the paid version. LazyBlocks is a better plugin than ACF imho and all our team members love it! We notice one hesitancy at many places if that people are so much into ACF. Huge number of entries that they cannot switch to your plugin even if they want to. Can you introduce a feature which fetch the post_meta and convert to your block attribute? 

It's easy to do for simple fields like text or textarea fields. More efforts will be for file upload and repeater fields.

**Comment by nk-o** [comment]
Hey. I'm not sure we will make such migration tool, because I have not yet seen such requests from users. If more people need such a feature, we will think about it.

**Comment by nk-o** [comment]
Closing this issue due to limited interest in the feature.
