### ISSUE TITLE
Error in widgets with classic_editor type

### ISSUE THREAD

**Issue by Grejods** [nk-crew/lazy-blocks#249]
### Issue description:
The block that has a classic_editor type won't work in the blocks style widgets and shows an error and cannot be previewed.

### Lazy Blocks Version:
2.5.3

### WordPress Version:
6.0

### Any helpful information to reproduce the issue (screenshots, code parts)
Just make a content block with a classic editor type and the problem will show up other types don't have this problem.

![Schermafbeelding 2022-06-28 om 11 02 29](https://user-images.githubusercontent.com/17969684/176140226-a1f5bc5d-77b9-4657-98f0-dfa88bcaa11f.png)
![Schermafbeelding 2022-06-28 om 11 03 10](https://user-images.githubusercontent.com/17969684/176140236-3ce3fd53-23b3-46bb-a606-0f5c826b4d98.png)

### Question:
Is there a solution for this issue ?
If not, is it possible to use the lazy-blocks in the classic widget mode ?

**Comment by mathiasselleslach** [comment]
@nk-o , when could we expect a new release of the plugin that would include this?

Thanks again for making the fix!
