### ISSUE TITLE
Set control value Programmatically?

### ISSUE THREAD

**Issue by janwidmer** [nk-crew/lazy-blocks#255]
### Issue description:
For a custom control, I need the possibility to set the control value programmatically. Is there an option to call a method, which sets the value of a control and also triggers a re-render?

If there is no method currently, could you provide some basic steps, how I could add it?

### Lazy Blocks Version:
2.5.3

### WordPress Version:
6.0.1

**Comment by davidwebca** [comment]
Hi! I'm not affiliated with the plugin creators, but I just saw this and I thought I would drop these links: 

https://lazyblocks.com/documentation/js-filters/lzb-constructor-controls-item/
https://lazyblocks.com/documentation/js-filters/lzb-constructor-control-settings/

These two JavaScript filters should get you somewhere, but I haven't tried them.

**Comment by nk-o** [comment]
Hey.

If you add a custom control and update the block attribute value using `onChange`, it will always triggers a re-rendering. As per example here - https://github.com/nk-crew/lazy-blocks-custom-control-template/blob/49d4b1f74104514cdb1ae9a4f2413fc47e35fe49/src/assets/js/CONTROL-NAME.js#L22-L36

Are you looking for something different?

**Comment by janwidmer** [comment]
Hey,

I am looking for a way to set the value of one control programmatically based on the value of another control when it changes.. the problem there is, that I don't have the context of control B in the change event of control A..

Is there an easy solution for that?

**Comment by nk-o** [comment]
Hey.

Look at the 3rd parameter in these filters named `props`. It is a props from the whole block, where you can find the block attributes and `setAttributes` function.

https://github.com/nk-crew/lazy-blocks/blob/4c27883d901e53486903af6a3be1047620a6967b/src/assets/editor/blocks/main/edit.js#L281-L295

See here examples on how to use it https://developer.wordpress.org/block-editor/getting-started/create-block/attributes/

**Comment by janwidmer** [comment]
Hey @nk-o thanks for pointing me to the right direction, using the attributes solved my problem :-)
