### ISSUE TITLE
Url field inside repeater does not work

### ISSUE THREAD

**Issue by neppers3** [nk-crew/lazy-blocks#260]
### Issue description:
I can not get any output from the field. It get stored in the admin. All other fields in repeater works fine. I can not see the url-field in the array at all.

### Lazy Blocks Version:
2.5.3

### WordPress Version:
6.0.1

### Any helpful information to reproduce the issue (screenshots, code parts)
Create a repeater who includes an url-field and try to echo it.

				<div class="row-full">
			<div class="container">

<?php if (!empty($attributes['tekst-over-rader'])): ?>
<h2 class="mt-5"><?php echo $attributes['tekst-over-rader']; ?></h2>
<?php endif; ?>
    <div class="row row-cols-1 row-cols-lg-3 gy-5 g-lg-5 mt-3 mb-5">
	
<?php foreach( $attributes['blokk'] as $inner ): ?>

  <div class="col">
    <div class="card h-100<?php if ($attributes['fargebakgrunn-pa-blokk']): ?> bg-light<?php endif; ?>">
<?php if ( $inner['bilde'] ): ?>
<picture>
<img class="card-img-top<?php if ($attributes['fargebakgrunn-pa-blokk']): ?><?php else: ?> rounded-end<?php endif; ?> rounded-top" src="<?php print wp_get_attachment_image_url($inner['bilde']['id'], 'artikkel_313px'); ?>" alt="<?php $get_alttext = get_post_meta($thumbnail_id, '_wp_attachment_image_alt', true); if(!empty($get_alttext)){ echo $get_alttext; } else { echo the_title(); }; ?>" title="<?php $get_imagetitle = get_the_title($thumbnail_id); if(!empty($get_imagetitle)){ echo $get_imagetitle; } else { echo the_title(); }; ?>">
</picture>
<?php endif; ?>
      <div class="card-body<?php if ($attributes['fargebakgrunn-pa-blokk']): ?> px-4<?php endif; ?> <?php if ($attributes['vis-dato-opprettet']): ?>pb-0<?php else: ?>pb-5<?php endif; ?>">
<?php if ($attributes['vis-knapper']): ?>
        <h2 class="card-title"><?php echo $inner['overskrift']; ?></h2>
<?php else: ?>
        <h2 class="card-title"><a href="<?php print_r($inner['artikkellink']); ?>" class="stretched-link text-black"><?php echo $inner['overskrift']; ?></a></h2>
<?php endif; ?>
        <div class="card-text"><?php echo $inner['tekst']; ?></div>
<?php if ($attributes['vis-knapper']): ?>
        <a href="<?php echo $inner['link']; ?>" class="btn btn-lg btn-outline-black">Se mer</a>
<?php endif; ?>
      </div>
<?php if ($attributes['vis-dato-opprettet']): ?>
  <div class="card-footer text-muted border-0 p-0 pb-3<?php if ($attributes['fargebakgrunn-pa-blokk']): ?> px-4<?php endif; ?>">
    <?php echo get_the_date(); ?>
  </div>
<?php endif; ?>
    </div>
  </div>

<?php endforeach; ?>
</div>

				</div>
			</div>

**Comment by neppers3** [comment]
Seems my code got lost in the post.

`				<div class="row-full">
			<div class="container">

<?php if (!empty($attributes['tekst-over-rader'])): ?>
<h2 class="mt-5"><?php echo $attributes['tekst-over-rader']; ?></h2>
<?php endif; ?>
    <div class="row row-cols-1 row-cols-lg-3 gy-5 g-lg-5 mt-3 mb-5">
	
<?php foreach( $attributes['blokk'] as $inner ): ?>

  <div class="col">
    <div class="card h-100<?php if ($attributes['fargebakgrunn-pa-blokk']): ?> bg-light<?php endif; ?>">
<?php if ( $inner['bilde'] ): ?>
<picture>
<img class="card-img-top<?php if ($attributes['fargebakgrunn-pa-blokk']): ?><?php else: ?> rounded-end<?php endif; ?> rounded-top" src="<?php print wp_get_attachment_image_url($inner['bilde']['id'], 'artikkel_313px'); ?>" alt="<?php $get_alttext = get_post_meta($thumbnail_id, '_wp_attachment_image_alt', true); if(!empty($get_alttext)){ echo $get_alttext; } else { echo the_title(); }; ?>" title="<?php $get_imagetitle = get_the_title($thumbnail_id); if(!empty($get_imagetitle)){ echo $get_imagetitle; } else { echo the_title(); }; ?>">
</picture>
<?php endif; ?>
      <div class="card-body<?php if ($attributes['fargebakgrunn-pa-blokk']): ?> px-4<?php endif; ?> <?php if ($attributes['vis-dato-opprettet']): ?>pb-0<?php else: ?>pb-5<?php endif; ?>">
<?php if ($attributes['vis-knapper']): ?>
        <h2 class="card-title"><?php echo $inner['overskrift']; ?></h2>
<?php else: ?>
        <h2 class="card-title"><a href="<?php print_r($inner['artikkellink']); ?>" class="stretched-link text-black"><?php echo $inner['overskrift']; ?></a></h2>
<?php endif; ?>
        <div class="card-text"><?php echo $inner['tekst']; ?></div>
<?php if ($attributes['vis-knapper']): ?>
        <a href="<?php echo $inner['link']; ?>" class="btn btn-lg btn-outline-black">Se mer</a>
<?php endif; ?>
      </div>
<?php if ($attributes['vis-dato-opprettet']): ?>
  <div class="card-footer text-muted border-0 p-0 pb-3<?php if ($attributes['fargebakgrunn-pa-blokk']): ?> px-4<?php endif; ?>">
    <?php echo get_the_date(); ?>
  </div>
<?php endif; ?>
    </div>
  </div>

<?php endforeach; ?>
</div>

				</div>
			</div>
`

**Comment by CullenJWebb** [comment]
Are the links properly saving when you edit the block?

I was having a similar issue when I inserted #test into the URL field without clicking the link confirmation dialog.

**Comment by nk-o** [comment]
It works in the dev build for me. Once the plugin will be updated, please, check it again.

![image](https://user-images.githubusercontent.com/14810891/197543528-be67f462-64ed-4599-a0e8-639d74d2a356.png)
