### ISSUE TITLE
How to Output 2 codes with same block

### ISSUE THREAD

**Issue by yousafblogger** [nk-crew/lazy-blocks#262]
Hello,

I've created a block, but I want 2 outputs. One to show the values in the table using shortcode, the other one is to show where I put the block.

I am going to be placing shortcode and block on the same page, but different locations one the page. 

Can anyone guide me with that. I've researched a lot. and I don't have a strong grip on PHP, that's why I am posting here.

**Comment by yousafblogger** [comment]
Anyone here!

**Comment by davidwebca** [comment]
Not sure your question is clear. Please provide an example and maybe screenshots of what you mean so that people can better help you.

**Comment by yousafblogger** [comment]
<img width="770" alt="Screen Shot 2022-09-29 at 9 14 02 AM" src="https://user-images.githubusercontent.com/68800668/192937327-8dac0932-15ed-4fe8-bcd9-090c055ab95a.png">

I wrote this code, for the output! but I want to use the same attributes to output a table, which can be placed in the article via shortcode.

I hope that I made my question clear!

**Comment by nk-o** [comment]
Hey.

If you want to reuse this output code, you can create a function inside your custom plugin or in the theme code and then try to call it inside a block and shortcode.

As an alternative, you can render the block inside your shortcode output. I have not tested this way, but I think it should work.

```php
$block_string = '<!-- wp:lazyblock/your-block-name {"attribute_name":"hello","blockId":"UNIQUE_ID_HERE","blockUniqueClass":"lazyblock-your-block-name-UNIQUE_ID_HERE"} /-->';

echo do_blocks( $block_string );
```

**Comment by yousafblogger** [comment]
Thanks for the reply!

But I want to use the same input to render another block. I don't want to use new inputs.
