### ISSUE TITLE
Feature request: Ability to register block styles, conditional logic to show/hide fields and different rendering per block style

### ISSUE THREAD

**Issue by davidwebca** [nk-crew/lazy-blocks#266]
### Issue description:
This is merely a feature request! Since you already provide the ability to create post type templates in the plugin, it would be amazing to also be able to create block styles right from the block creator, and even possibly have options to select a different template per block style.

My solution for this now was to use regsiterBlockStyle in JavaScript in the editor (which is just a glorified way of adding a class to the block "is-style-nameofthestyle" and adding a live preview of the style. Then, I parse out the class to branch out my rendering to different files if need be.

```php
$blockStyle = 'default';
if(isset($attributes['className'])) {
    $blockStyle = preg_match('/is-style-([^\s]+)/', $attributes['className'], $matches) ? $matches[1] : 'default';
}
/* ... check if separate file exist if using template files, etc. */
```

In summary
1. Option to create block styles (registerBlockStyle) straight from the block creator admin
2. Conditional logic to show/hide some fields depending on the block style
3. Option to render a different view altogether depending on the block style

### Lazy Blocks Version:
3.0.0

### WordPress Version:
6.1

### Any helpful information to reproduce the issue (screenshots, code parts)
I personally hijack the rendering of template files with the filter to render Laravel Blade views since I use Bedrock's Sage starter theme. Here's my full solution:

```php
/**
 * Allow using blade templating engine inside Lazy Blocks
 */
add_filter('lzb/block_render/output', function($result, $attributes, $context) {
    global $lazyblock_counters;
    if(!is_array($lazyblock_counters)) {
        $lazyblock_counters = [];
    }

    if(isset($attributes['lazyblock']) && isset($attributes['lazyblock']['slug'])) {
        $bladeview = false;
        $viewSlug = $attributes['lazyblock']['slug'];
        $blockStyle = 'default';
        if(isset($attributes['className'])) {
            $blockStyle = preg_match('/is-style-([^\s]+)/', $attributes['className'], $matches) ? $matches[1] : 'default';
        }

        $blockStyle = apply_filters( 'lzb_custom_block_style', $blockStyle, $attributes );

        /**
         * First, we check if a specific view is specified for the block style + context
         * Then block style alone
         * Then default block name + context
         * Then default block name
         */
        if(\Roots\view()->exists($viewSlug.'-'.$blockStyle.'-'.$context)) {
            $bladeview = $viewSlug.'-'.$blockStyle.'-'.$context;
        }elseif(\Roots\view()->exists($viewSlug.'-'.$blockStyle)) {
            $bladeview = $viewSlug.'-'.$blockStyle;

        }elseif(\Roots\view()->exists($viewSlug.'-'.$context)) {
            $bladeview = $viewSlug.'-'.$context;
        }elseif(\Roots\view()->exists($viewSlug)) {
            $bladeview = $viewSlug;
        }

        if($bladeview) {
            if(!isset($lazyblock_counters[$attributes['lazyblock']['slug']])) {
                $lazyblock_counters[$attributes['lazyblock']['slug']] = 0;
            }
            $lazyblock_counters[$attributes['lazyblock']['slug']]++;
            $result = \Roots\view($bladeview, compact(['result', 'attributes', 'context']))->render();
        }
    }

    return $result;
}, 0, 3);
````

Note: I created a $lazyblock_counters global to be able to count the similar blocks used on the page and create a simili ID if the person hasn't passed a custom anchor, as such, making sure each block as a different ID. This shouldn't be necessary anymore in practice and can be ignored.

**Comment by nk-o** [comment]
Thank you for your code example.

I'm not sure about different render callbacks per style, but the possibility to add conditions to controls based on selected styles is dope. We have to add it in the next Pro update for sure :)
