### ISSUE TITLE
React Error since Plugin Update

### ISSUE THREAD

**Issue by janwidmer** [nk-crew/lazy-blocks#272]
### Issue description:
Since the last Plugin Update, I get a react error when using a component within the innerBlocks control:
<img width="2468" alt="image" src="https://user-images.githubusercontent.com/3381820/203555270-67d2feca-808f-43f4-9cda-8b65a0872ce0.png">

### Lazy Blocks Version:
3.1.0

### WordPress Version:
6.1.1

### Any helpful information to reproduce the issue (screenshots, code parts)
The outer and inner components export are attached to the ticket.
[lzb-export-blocks-2022-11-23.json.zip](https://github.com/nk-crew/lazy-blocks/files/10075774/lzb-export-blocks-2022-11-23.json.zip)

The component is an accordion, where accordion items can be inserted. In Every Accordion Item, Components can be inserted again..

**Comment by CGTS** [comment]
Is there a timeline for when the inner-block fix will be pushed out? With the error I am not able to update any of the content in those blocks.
