### ISSUE TITLE
Feature Request: FileSelector -> .json

### ISSUE THREAD

**Issue by plueschpruem** [nk-crew/lazy-blocks#275]
Can we have .json added to the file selector list please?
thanks!

**Comment by nk-o** [comment]
File control uses the standard set of mime types available in WordPress

https://github.com/nk-crew/lazy-blocks/blob/7923ba6ea8cf5f7c8741cbc15fdc0230d43dddc4/classes/class-admin.php#L141

I think you should extend it using WP filters.
