### ISSUE TITLE
Gutenberg plugin breaks Blocks constructor

### ISSUE THREAD

**Issue by jakobwiens7** [nk-crew/lazy-blocks#278]
### Issue description:
When trying to create a new block (or edit existing ones) while having the Gutenberg plugin activated, it seems that no styles are being applied to the Blocks constructor. This makes it almost impossible to create/edit blocks unless you deactivate Gutenberg.

### Lazy Blocks Version:
Lazy Blocks v3.3.0
Lazy Blocks Pro v3.3.0

### WordPress Version:
Wordpress v6.1.1
Gutenberg v14.9.0 and higher

### Any helpful information to reproduce the issue (screenshots, code parts)
From what i noticed, Gutenberg 14.9.0 or higher now causes the Blocks constructor to be placed inside an iframe when using a block theme, which results in the relevant inline CSS styles not being applied anymore (or maybe not even enqeued inside the editor). I assume this will be a major issue when WP 6.2 lands next month, since Gutenberg features get merged into core.

![lazyblocks-bug_screenshot](https://user-images.githubusercontent.com/37865257/219064692-60a1c747-5965-4e89-8d51-ab669795fddf.jpg)

**Comment by nk-o** [comment]
Looks like WordPress 6.2 does not have an iframe preview, so we can wait for a better implementation and check if this bug will be addressed by the Gutenberg team.

Currently, we include styles of components right inside JS, and these styles are not included inside the iframe. Example - https://github.com/nk-crew/lazy-blocks/blob/3a1b9cafa1dea647d17f07edcebfcff1b36eccbd/assets/components/tab-panel/index.js

**Comment by davidwebca** [comment]
Just to chime in, WordPress 6.3 might get full iframed styles. It will be landing in Gutenberg 16, so WP 6.3 might get it, or not too long after that. https://github.com/WordPress/gutenberg/pull/48286
