### ISSUE TITLE
Color Picker not returning Slug

### ISSUE THREAD

**Issue by janwidmer** [nk-crew/lazy-blocks#284]
### Issue description:
When using the color picker control in combination with Outout Method "Theme Template", I always just get the color hex code, but not the slug. I have set the control output format to be Array (Color & Slug), but it does not change anything.

I am using the `render_block` filter of gutenberg to wrap my components with some additional markup / classes. In that place, I want to add a class using the color slug of the chosen color.

By accessing `$block['attrs']['backgroundColor']` within the filter `render_block` I do not get an array (as I would expect based on the [docs](https://www.lazyblocks.com/docs/blocks-controls/color-picker/))

### Lazy Blocks Version:
3.3.0

### WordPress Version:
6.2.2

### Any helpful information to reproduce the issue (screenshots, code parts)
The issue has already existed once: https://github.com/nk-crew/lazy-blocks/issues/228

Container Block Component with Background Colors:
<img width="2018" alt="image" src="https://github.com/nk-crew/lazy-blocks/assets/3381820/257bf9a6-644f-4a88-b67b-a2691cf568d7">

Theme.json with Color Palette:
<img width="565" alt="image" src="https://github.com/nk-crew/lazy-blocks/assets/3381820/e3dbdf36-eb86-41c1-be92-d8546f2d8d9b">

Output of `echo $block['attrs']['backgroundColor']`
<img width="198" alt="image" src="https://github.com/nk-crew/lazy-blocks/assets/3381820/22725d9e-a3d7-4b50-a584-01488c400431">

**Comment by nk-o** [comment]
Hi @janwidmer,

Inside the block attributes, we just save the color code. And by this call `echo $block['attrs']['backgroundColor']` you only access this raw color code.

Slug is specially prepared for the block code https://www.lazyblocks.com/docs/blocks-code/overview/ and you can access it using the `$attributes` variable https://www.lazyblocks.com/docs/blocks-controls/color-picker/

Regards,
Nikita.

**Comment by janwidmer** [comment]
Hi @nk-o, 

I need the slug within the Gutenberg filter `render_block` (where as I understand your answer currently only the raw color code is accessible). Would it be an option to add the slug to the block attributes too?

Thanks and BR
Jan

**Comment by janwidmer** [comment]
@nk-o never mind, I wrote my own function to get the slug for the color value. :)
