### ISSUE TITLE
504 and 429 Too Many Requests

### ISSUE THREAD

**Issue by gettonet** [nk-crew/lazy-blocks#285]
### Issue description:
When running on WPEngine hosting, blocks cannot render in editor due to 504 errors; also receive 429 Too Many Requests.
WPEngine support say to reach plugin developer to try to reduce number of requests caused by the plugin.

### Lazy Blocks Version:
3.3.0.

### WordPress Version:
6.2.2.

**Comment by gettonet** [comment]
PRO fixed the issue.

**Comment by nk-o** [comment]
Added troubleshooting page in the documentation https://www.lazyblocks.com/docs/troubleshooting/receive-a-504-and-429-error-too-many-requests/
