### ISSUE TITLE
Undefined index: styles in Applications/MAMP/htdocs/isabelgroup/wp-content/plugins/lazy-blocks/classes/class-blocks.php

### ISSUE THREAD

**Issue by orso081980** [nk-crew/lazy-blocks#286]
### Issue description:
There was a critical error with the array $styles (undefined index)
Notice: Undefined index: styles in /Applications/MAMP/htdocs/isabelgroup/wp-content/plugins/lazy-blocks/classes/class-blocks.php on line 1394

### Lazy Blocks Version:
Last one 3.4.0

### WordPress Version:
6.2.2

### Any helpful information to reproduce the issue (screenshots, code parts)
It seems a critical error, it brakes our pipelines

**Comment by plueschpruem** [comment]
OK, a quickfix for me was changing line 1394 from:
`'styles'          => $block['styles'],`
to:
`'styles'          => isset($block['styles']) ? $block['styles'] : null,`

This checks if the style is set and returns either that, or null – but wont error.
I have no idea where to exactly insert what type of array member – no time to research today – but i guess it is simple like adding it to our blocks declarations.
