### ISSUE TITLE
Remove wrapper <div class="lazyblock-inner-blocks"> when using <InnerBlocks /> component

### ISSUE THREAD

**Issue by gettonet** [nk-crew/lazy-blocks#287]
### Issue description:
When replacing deprecated InnerBlock control with <InnerBlocks />, wrapper appears.
Using lzb/block_render/allow_wrapper filter does not help.

### Lazy Blocks Version:
3.4.0

**Comment by gettonet** [comment]
I found out it's hardcoded; should be able to be filtered.
`$result = preg_replace( '/<InnerBlocks([\S\s]*?)\/>/', '<div class="lazyblock-inner-blocks">' . $content . '</div>', $result );`

What's the use of wrapper anyway?

**Comment by nk-o** [comment]
The wrapper is added by default in the editor and this is why we also add it in the frontend code.

![Shot 2023-06-30 at 08 18 16](https://github.com/nk-crew/lazy-blocks/assets/14810891/1ea14561-b9eb-4b3a-aa85-efa3e5380127)

In the coming update will be added filter to remove this wrapper on the frontend https://www.lazyblocks.com/docs/php-filters/lzb-block_render-allow_inner_blocks_wrapper/.

Also will be added an additional option to change the wrapper class, just use it like this - `<InnerBlocks className="my-custom-class" />`.
