### ISSUE TITLE
Error on Pro plugin activation: The plugin does not have a valid header.

### ISSUE THREAD

**Issue by gettonet** [nk-crew/lazy-blocks#290]
### Issue description:
After installing and clicking Activate, Wordpress reports error: "The plugin does not have a valid header."
After returning to plugins page, clicking on "Activate" activates plugin and all is fine.

### Lazy Blocks Version:
3.4.2

### WordPress Version:
6.2.2.

**Comment by nk-o** [comment]
Looks like when we just uploaded zip file, WP determine the wrong file of the plugin.

![Shot 2023-07-10 at 09 19 10](https://github.com/nk-crew/lazy-blocks/assets/14810891/90b4230d-bd95-48ac-9821-a558d920d40e)

This button contains this URL:

`https://example/wp-admin/plugins.php?action=activate&plugin=lazy-blocks-pro%2Fcore-plugin%2Flazy-blocks.php`

While the correct one is:

`https://example/wp-admin/plugins.php?action=activate&plugin=lazy-blocks-pro%2Flazy-blocks-pro.php`

I'm not sure how to fix this correctly. Maybe we have to remove the header comment from the core plugin php file (`lazy-blocks-pro/core-plugin/lazy-blocks.php`)
