### ISSUE TITLE
Custom type rendering in the editor 

### ISSUE THREAD

**Issue by MohcinBN** [nk-crew/lazy-blocks#292]
### Issue description:
I'm trying to create a custom control type named "text2" for the LazyBlocks plugin. I loaded the class created in my editor but when I call the type "text2" in my block controls it did not appears.

I think i have an issue in rendering the HTML in this case, here how i tried to do it in my class:

        public function render_field($attributes): void
        {
            printf('<input type="text" name="%s" class="lazyblocks-text2" value="%s" />', esc_attr($this->get_field_name()), esc_attr($this->get_field_value($attributes)));
        }

### Lazy Blocks Version:
The latest version

### WordPress Version:
The latest version

### Any helpful information to reproduce the issue (screenshots, code parts)
the whole class: 

```
<?php
/**
 * Text input.
 *
 * @package lzb-text2
 */

if (!defined('ABSPATH')) {
    exit;
}

if (!class_exists('Lzb_Control_Text2')) :
    /**
     * Lzb_Control_Text2 class.
     *
     * LazyBlocks_Control - https://github.com/nk-o/lazy-blocks/blob/master/src/controls/_base/index.php
     */
    class Lzb_Control_Text2 extends LazyBlocks_Control
    {
        /**
         * Constructor
         */
        public function __construct()
        {
            echo 'Custom control type text2 is loaded';
            $this->name = 'text2';
            $this->icon = '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M3.99988 19.25H12.9999" stroke="currentColor" stroke-width="1.5"/><path d="M3.99988 15.25H19.9999" stroke="currentColor" stroke-width="1.5"/><path d="M8.99429 10.1029H6.08L5.41714 12H4L6.84572 4H8.22857L11.0743 12H9.65714L8.99429 10.1029ZM8.53714 8.82286L7.54286 5.96571L6.53714 8.82286H8.53714Z" fill="currentColor"/></svg>';
            $this->type = 'text';
            $this->label = __('Text2', 'lazy-blocks');
            $this->attributes = array(
                'placeholder' => '',
                'characters_limit' => '',
            );
            $this->restrictions = array(
                'translate_settings' => true,
            );

            parent::__construct();

        }

        public function render_field($attributes): void
        {
            printf('<input type="text" name="%s" class="lazyblocks-text2" value="%s" />', esc_attr($this->get_field_name()), esc_attr($this->get_field_value($attributes)));
        }

    }


    new Lzb_Control_Text2();

endif;
```

**Comment by nk-o** [comment]
Hi,

To create a custom control you have to create React code to render control in the editor, a single PHP class will not create a custom control automatically. Please, read here how to create custom control and see the code example with ready to use custom control https://www.lazyblocks.com/docs/examples/create-custom-control/

p.s. what is `render_field` in your example? Our plugin does not have such methods.

Regards,
Nikita.
