### ISSUE TITLE
Post control bug: cannot remove single value on multiselect

### ISSUE THREAD

**Issue by gettonet** [nk-crew/lazy-blocks#297]
## Issue description:

When post control is used in multiselect mode, first the layout is not good (can be fixed using css), but what is worse single value is not being removed by clicking "X" . Only all values can be cleared.

![image](https://github.com/nk-crew/lazy-blocks/assets/14810891/2d6aa0b8-4115-4cac-809c-6e0115f65292)

## Lazy Blocks Version:

Lazy Blocks Pro 3.5.1

## WordPress Version:

6.3.1

## Any helpful information to reproduce the issue (screenshots, code parts)

How I fixed layout issue:
```.lazyblocks-control-posts .lazyblocks-component-select div[role="button"] { max-width: 100%; } .lazyblocks-control-posts .lazyblocks-component-select div[role="button"] > div > div{ white-space: normal !important; } ```

**Comment by nk-o** [comment]
fixed in https://github.com/nk-crew/lazy-blocks/commit/79ef4befdc451ef09b9e256cc343f44362211ba2 https://github.com/nk-crew/lazy-blocks/commit/05a065890eecf74ab76e8c7fe7af0b2a13544d78
