### ISSUE TITLE
WYSIWYG classic editor does't work 

### ISSUE THREAD

**Issue by RandM18** [nk-crew/lazy-blocks#305]
### Issue description: 
The classic WYSIWYG editor is not initialized. An empty inactive field appears. Tell me what can be done about it?

### Any helpful information to reproduce the issue (screenshots, code parts)
![image](https://github.com/nk-crew/lazy-blocks/assets/50764254/1f4082ac-45e2-473e-ba51-b3530d7a3f9f)

**Comment by nk-o** [comment]
This is a bug, which appears in the iframed editor. It is not possible to init the Classic control inside Content. This bug will be fixed in the coming plugin update. Already fixed in the dev build https://github.com/nk-crew/lazy-blocks/pull/304

**Comment by repli2dev** [comment]
@nk-o Hi, this fix with providing `Open Editor` button is quite annoying when having more such fields in one blocks as it hides the content so every interaction needs to be done through the button.

Is there any other way how to do it or allow it when non problematic?

**Comment by nk-o** [comment]
@repli2dev since Gutenberg switched its editor to an iframe, the Classic control stopped functioning. I'm not sure if there are other options. When we tried to integrate this control into the iframe, we were unsuccessful, so we opted to use a popup, similar to the Gutenberg Classic block.
