### ISSUE TITLE
[Issue Report] Blocks containing HTML5 elements display errors and do not render when editing an article

### ISSUE THREAD

**Issue by kurikimuchi** [nk-crew/lazy-blocks#307]
Report an unexpected error.

---

## Issue description:
Since updating the plugin to **v3.6**, there has been a problem with article editing.
If **`"editor.php"` contains HTML5 tags**, it will **not be rendered only when editing**.
This is probably because the `"loadHTML"` function does not support HTML5. (#303)

### To Reproduce

1. create a new lazy-blocks block
2. create a new `"editor.php"` template file
3. write **HTML5 elements in `"editor.php"`** (e.g. `<nav>`,`<section>`,`<figure>`...)
4. insert block in article
5. **"Error loading block preview"** is displayed and does not render

### Warning Message

```
Error loading block preview: Please ensure that the output is a valid HTML structure.
```

## Version:

- [Lazy Blocks v3.6.0](https://github.com/nk-crew/lazy-blocks/releases/tag/v3.6.0)
- WordPress 6.4.3

## Screenshot:
![image](https://github.com/nk-crew/lazy-blocks/assets/42775886/42953d27-88a4-435a-b04f-36381ad00fa2)

## Example Code:
[ editor.php ]
```
<div>
  <nav></nav>
</div>
```

---
Best Regards.

**Comment by nk-o** [comment]
Thank you for info, fixed in v3.6.1
