### ISSUE TITLE
Blocks crashes after entering URL

### ISSUE THREAD

**Issue by patrickpalfinger** [nk-crew/lazy-blocks#308]
Since the latest update to LazyBlocks Pro 3.6.1, the whole Block crashes after entering an URL and clicking on Enter.

### WordPress Version: 6.5

![Screenshot 2024-04-04 134056](https://github.com/nk-crew/lazy-blocks/assets/117353416/e0b3e1a8-6df1-490a-8cdb-f676b3bab513)

EDIT: I downgraded to WordPress 6.4.4 for now, hope this issue gets resolved in the near future

**Comment by nk-o** [comment]
It looks like URL control no longer works inside the Content. Please use Inspector instead.

**Comment by benjaminr1986** [comment]
Is this likely to be fixed? Or is it a Wordpress issue rather than Lazyblocks?

**Comment by madebyfabian** [comment]
@benjaminr1986 Having the same issue. I've read in another issue/discussion, that this is a WordPress editor issue, since the block editor was not designed to handle url inputs.

**Comment by benjaminr1986** [comment]
Thanks - yeah ok. Will keep this in mind on my next project with lazyblocks. Such a great plugin overall.

**Comment by MohcinBN** [comment]
Hey everyone, it's likely an issue with the WordPress editor Gutenberg itself interfering with LazyBlocks. A simple change of the type from URL to text seems to be working in case you did not want to change the placement from content to the inspector section. 

This may help someone!
