### ISSUE TITLE
Multiline paste to rich_text not working

### ISSUE THREAD

**Issue by repli2dev** [nk-crew/lazy-blocks#309]
### Issue description:
When I paste a multiline string into a `rich_text` then I get `[object Object]` (totaling count of the new lines)

<img width="856" alt="Snímek obrazovky 2024-04-16 v 9 39 36" src="https://github.com/nk-crew/lazy-blocks/assets/475549/c9adfbad-7f82-4862-89d8-63cf09712a66">

Pasting a simple text/word works as expected.

### Lazy Blocks Version:

3.6.1 (latest)

### WordPress Version:

6.5.2 (latest)

**Comment by nk-o** [comment]
Multiline is deprecated in RichText component
