### ISSUE TITLE
Error in widgets with classic_editor type

### ISSUE THREAD

**Issue by MohcinBN** [nk-crew/lazy-blocks#311]
### Issue description:

The block that has a classic_editor type won't work in the blocks style widgets and shows an error and cannot be previewed.
The error message: "This block has encountered an error and cannot be previewed."

### Lazy Blocks Version:

Version 3.6.1

### WordPress Version:

Version 6.5.2

### Any helpful information to reproduce the issue (screenshots, code parts)

![Screenshot from 2024-04-25 14-52-23](https://github.com/nk-crew/lazy-blocks/assets/11162382/f4ed5adb-ef13-40a2-a731-a3f9210768f9)

**Comment by golfbal** [comment]
@nk-o Any idea when this might get fixed? We currently cannot edit any widget blocks...

**Comment by MohcinBN** [comment]
Hi @nk-o please can you look at this as soon as you can, we are currently stuck at this point :)
