### ISSUE TITLE
How to modify the value of a block attribute in a php filter/hook?

### ISSUE THREAD

**Issue by aayla-secura** [nk-crew/lazy-blocks#313]
Is there a way to modify the value of a block attribute in a way that's reflected in the editor? I.e. when a user changes the value of one attribute in the editor, I want to update the value of another attribute in php (I know I can do it in JavaScript), and have that reflected on the editor and then saved in the block. None of the php filters I tried, such as `lzb/block_render/attributes` seem to allow me to do this. The hook does fire when an attribute is updated in Gutenberg, I change the value of an attribute, return the updated attributes, but nothing is changed in the Editor or when the page is saved.

**Comment by nk-o** [comment]
PHP does not allow you to change the block attribute. You can only filter the current saved attribute and replace it to render a different value, but this does not change the saved content. If you want to make changes in the editor, you will likely need to add JS hooks and manually change block attributes.

You can listen for changes using this filter: https://www.lazyblocks.com/docs/js-filters/lzb-editor-control-updatevalue/. However, to change the value of another attribute, you will need to make Gutenberg API calls. We don't have a solution for this.
