### ISSUE TITLE
Image URL option in Image control

### ISSUE THREAD

**Issue by nk-o** [nk-crew/lazy-blocks#70]
The same like in Image block:

![image](https://user-images.githubusercontent.com/14810891/55063408-f6543980-5088-11e9-8982-8a93865df118.png)

We need to add an option to allow this button, so by default it will not be visible.

Related topic: https://wordpress.org/support/topic/insert-image-from-url-3/

**Comment by danodna** [comment]
Please add the 'Insert from URL' option for the Lazy Blocks image insert field, so it is using the standard WordPress image block options: 1) upload, 2) media library and 3) insert from url.
Thank you!
