### ISSUE TITLE
Get post,categories,taxonomies

### ISSUE THREAD

**Issue by ravishakya** [nk-crew/lazy-blocks#8]
The plugin is great and very useful. I know the plugin is in early stage but can we have the possibility of getting posts, categories ??

eg. I want to create a testimonial section, for that, I want to select categories and from that categories, I want to get the post. Will that be possible to get all categories ??

**Comment by matt3224** [comment]
Run into needing this on almost every project, would be great if lazyblocks could handle this out of the box.

Ideally i'd like to be able to select an individual post type post, an individual taxonomy item and X posts from a post type

**Comment by janwidmer** [comment]
@nk-o I created a select dynamic control based on your [custom control template](https://github.com/nk-o/lazy-blocks-custom-control-template). Would you accept a PR if I would transform it to a regular control based on this repo or should I rather publish it as a separate wordpress plugin?

**Comment by nk-o** [comment]
@janwidmer we have plans to make this control in the Pro plugin version. You can make a separate plugin for it.

**Comment by janwidmer** [comment]
@nk-o ok thanks for the quick reply. :-)

**Comment by janwidmer** [comment]
@ravishakya @matt3224 i published a plugin, if someone wants to give it a try: https://wordpress.org/plugins/lzb-select-dynamic/

**Comment by demahagit** [comment]
@janwidmer I downloaded your plugin https://wordpress.org/plugins/lzb-select-dynamic/   Its not working inside the repeater in lazy block. Anything i can tweak to make it work.

**Comment by janwidmer** [comment]
@demahagit could you please open an issue in my repo https://github.com/janwidmer/lzb-select-dynamic and post any helpful information (Printscreen / JS Exception from Console..) there?

**Comment by demahagit** [comment]
Hello Nk,


It's working now. I have created another issue to get posts as per the
category selected.

Regards,
Deepti

**Comment by nk-o** [comment]
This feature is available in the Lazy Blocks Pro https://www.lazyblocks.com/pro/
